// Seed script: create iPhone 15 product with uploaded images
import { config } from "dotenv";
config({ path: path.resolve(process.cwd(), ".env.local") });
import mongoose from "mongoose";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import fs from "fs";
import path from "path";

const R2 = new S3Client({
  region: "auto",
  endpoint: `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
  credentials: {
    accessKeyId: process.env.R2_ACCESS_KEY_ID!,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
  },
});

const BUCKET = process.env.R2_BUCKET_NAME!;
const PUBLIC_URL = process.env.R2_PUBLIC_URL!;
const SLUG = "apple-iphone-15";

async function uploadImage(filePath: string, key: string, contentType: string) {
  const body = fs.readFileSync(filePath);
  await R2.send(new PutObjectCommand({ Bucket: BUCKET, Key: key, Body: body, ContentType: contentType }));
  console.log(`✅ Uploaded: ${PUBLIC_URL}/${key}`);
  return `${PUBLIC_URL}/${key}`;
}

async function main() {
  // 1. Upload images to R2
  const images = [];
  const files = [
    { src: "/tmp/iphone15_blue_hi.jpg", dest: `products/${SLUG}/001.jpg`, type: "image/jpeg" },
    { src: "/tmp/iphone15_pink_hi.jpg", dest: `products/${SLUG}/002.jpg`, type: "image/jpeg" },
    { src: "/tmp/iphone15_green_hi.jpg", dest: `products/${SLUG}/003.jpg`, type: "image/jpeg" },
  ];
  for (const f of files) {
    const url = await uploadImage(f.src, f.dest, f.type);
    images.push(url);
  }

  // 2. Connect to MongoDB and create product
  await mongoose.connect(process.env.MONGODB_URI!);

  // Define minimal schema inline
  const ProductSchema = new mongoose.Schema({
    name: String, slug: String, sku: String, subtitle: String, description: String,
    price: Number, originalPrice: Number, category: String, categorySlug: String,
    subcategory: String, condition: { type: String, enum: ["New", "Refurbished", "Used"] },
    brand: String, images: [String], specs: { type: Map, of: String },
    stock: Number, featured: Boolean, published: Boolean, variants: [],
  }, { timestamps: true });

  const Product = mongoose.models.Product || mongoose.model("Product", ProductSchema);

  // Check if product already exists
  const existing = await Product.findOne({ slug: SLUG });
  if (existing) {
    console.log("⚠️  Product already exists, updating images and details...");
    existing.set({
      name: "Apple iPhone 15",
      subtitle: "Dynamic Island. 48MP camera. USB-C.",
      description: `The iPhone 15 features a gorgeous 6.1-inch Super Retina XDR display with Dynamic Island. Powered by the A16 Bionic chip, it delivers incredible performance and all-day battery life.\n\nThe advanced camera system includes a 48MP main camera and a 12MP ultra-wide camera, perfect for capturing stunning photos and videos. With USB-C, Ceramic Shield front, and an aerospace-grade aluminium design, the iPhone 15 is built to last.\n\nAvailable in Blue, Pink, Green, Yellow, and Black.`,
      price: 15499,
      originalPrice: 18999,
      category: "Smartphones",
      categorySlug: "it-hardware",
      subcategory: "smartphones",
      condition: "New",
      brand: "Apple",
      images,
      specs: new Map([
        ["Display", "6.1\" Super Retina XDR OLED"],
        ["Chip", "A16 Bionic"],
        ["Main Camera", "48MP f/1.6"],
        ["Ultra Wide Camera", "12MP f/2.4"],
        ["Front Camera", "12MP TrueDepth"],
        ["Storage", "128GB"],
        ["Battery", "Up to 20 hours video playback"],
        ["Charging", "USB-C, MagSafe wireless"],
        ["SIM", "Dual eSIM"],
        ["Water Resistance", "IP68"],
        ["Weight", "171g"],
        ["OS", "iOS 17"],
      ]),
      stock: 25,
      featured: true,
      published: true,
    });
    await existing.save();
    console.log(`✅ Updated product: ${existing.name} (SKU: ${existing.sku})`);
    console.log(`   ${existing._id}`);
  } else {
    const product = await Product.create({
      name: "Apple iPhone 15",
      slug: SLUG,
      sku: "", // auto-generated by API but we're inserting directly
      subtitle: "Dynamic Island. 48MP camera. USB-C.",
      description: `The iPhone 15 features a gorgeous 6.1-inch Super Retina XDR display with Dynamic Island. Powered by the A16 Bionic chip, it delivers incredible performance and all-day battery life.\n\nThe advanced camera system includes a 48MP main camera and a 12MP ultra-wide camera, perfect for capturing stunning photos and videos. With USB-C, Ceramic Shield front, and an aerospace-grade aluminium design, the iPhone 15 is built to last.\n\nAvailable in Blue, Pink, Green, Yellow, and Black.`,
      price: 15499,
      originalPrice: 18999,
      category: "Smartphones",
      categorySlug: "it-hardware",
      subcategory: "smartphones",
      condition: "New",
      brand: "Apple",
      images,
      specs: {
        "Display": "6.1\" Super Retina XDR OLED",
        "Chip": "A16 Bionic",
        "Main Camera": "48MP f/1.6",
        "Ultra Wide Camera": "12MP f/2.4",
        "Front Camera": "12MP TrueDepth",
        "Storage": "128GB",
        "Battery": "Up to 20 hours video playback",
        "Charging": "USB-C, MagSafe wireless",
        "SIM": "Dual eSIM",
        "Water Resistance": "IP68",
        "Weight": "171g",
        "OS": "iOS 17",
      },
      stock: 25,
      featured: true,
      published: true,
      variants: [],
    });
    console.log(`✅ Created product: ${product.name} (SKU: ${product.sku})`);
    console.log(`   ID: ${product._id}`);
  }

  await mongoose.disconnect();
  console.log("\n🎉 Done! Product is live at https://lab.impactstore.co.za/products/apple-iphone-15");
}

main().catch((err) => { console.error(err); process.exit(1); });
